"use strict";
(()=>{let S=null;
 const $=id=>document.getElementById(id),fmt=n=>Math.round(n).toLocaleString("fr-FR"),euro=n=>fmt(n)+" €";
 const evol=[ [100,"TRANSCENDANT","brian_lvl_100_transcendant"],[95,"PRÉ-TRANSCENDANT","brian_lvl_095_pre_transcendant"],[84,"ASCENDANT II","brian_lvl_084_ascendant_2"],[75,"ASCENDANT","brian_lvl_075_ascendant"],[62,"MAÎTRE SUPÉRIEUR","brian_lvl_062_maitre_superieur"],[50,"MAÎTRE","brian_lvl_050_maitre"],[35,"ÉLITE","brian_lvl_035_elite"],[20,"VÉTÉRAN","brian_lvl_020_veteran"],[17,"AGUERRI","brian_lvl_017_aguerri"],[10,"COMBATTANT","brian_lvl_010_combattant"],[5,"DÉTERMINÉ","brian_lvl_005_determine"],[1,"RECRUE","brian_lvl_001_base"] ];
 function clock(){let d=new Date;$("clock").textContent=d.toLocaleTimeString("fr-FR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Paris"});$("date").textContent=d.toLocaleDateString("fr-FR",{weekday:"long",day:"numeric",month:"long",timeZone:"Europe/Paris"}).toUpperCase()}clock();setInterval(clock,1000);
 function quotes(){let q=JSON.parse(localStorage.getItem("playerQuotes")||"{}");$("quoteTop").textContent="« "+(q.top||"Les petites actions d’aujourd’hui créent les grandes victoires de demain.")+" »";$("quotePlayer").textContent="« "+(q.player||"Un meilleur toi construit un meilleur monde.")+" »";$("quoteInputTop").value=q.top||"Les petites actions d’aujourd’hui créent les grandes victoires de demain.";$("quoteInputPlayer").value=q.player||"Un meilleur toi construit un meilleur monde."}quotes();
 function settings(){let g=S?.goals||{},f=S?.finance||{},cfg=JSON.parse(localStorage.getItem("playerGameSettings")||"{}");let fields=[["monthlyBudget","Budget mensuel (€)",cfg.monthlyBudget??f.monthlyBudget??1000],["readingGoal","Lecture / jour (pages)",cfg.readingGoal??g.reading??10],["learningGoal","Apprentissage / jour (minutes)",cfg.learningGoal??g.learning??30],["sportGoal","Sport / semaine",cfg.sportGoal??g.sport??4],["nutritionGoal","Repas conformes / jour",cfg.nutritionGoal??g.nutrition??3],["workGoal","Actions emploi / jour",cfg.workGoal??g.work??1]];$("settingsForm").innerHTML=fields.map(([k,l,v])=>`<label>${l}<input name="${k}" type="number" min="0" value="${v}"></label>`).join("")}
 function render(s){S=s;$("globalLevel").textContent=s.global.level;$("globalXp").textContent=fmt(s.globalXp);$("globalDetail").textContent=`${fmt(s.global.xpIntoLevel)} / ${fmt(s.global.nextFloor-s.global.currentFloor)} XP`;$("globalBar").style.width=s.global.progress+"%";$("modeName").textContent=s.difficulty.name;
  const defs=[["LECTURE","lecture",s.goals.reading+" p/j"],["APPRENTISSAGE","apprentissage",s.goals.learning+" min/j"],["SPORT","sport",s.sportWeek.sessions+" / "+s.goals.sport+" sem."],["NUTRITION","nutrition",s.goals.nutrition+" repas/j"],["RECHERCHE D'EMPLOI","travail",s.goals.work+" action/j"],["FINANCE","finance","budget"]];
  $("statGrid").innerHTML=defs.map(([n,k,obj])=>{let a=s.attrs[k];return `<article class="stat"><header><b>${n}</b><span>NIV. ${a.level}</span></header><strong>${fmt(a.xp)} XP</strong><small>${obj}</small><div class="bar"><i style="width:${a.progress}%"></i></div></article>`}).join("");
  $("budget").textContent=euro(s.finance.monthlyBudget);$("spent").textContent=euro(s.finance.spentThisMonth);$("remaining").textContent=euro(s.finance.budgetRemaining);$("financeBar").style.width=Math.min(100,s.finance.monthlyBudget?100*s.finance.spentThisMonth/s.finance.monthlyBudget:0)+"%";$("trajectory").textContent="Écart à la trajectoire : "+(s.finance.trajectoryGap>=0?"+":"")+euro(s.finance.trajectoryGap);
  $("weekText").textContent=`SPORT CETTE SEMAINE : ${s.sportWeek.sessions} / ${s.goals.sport}`;$("smoke").textContent=`SANS CIGARETTE : ${s.smoking.streak} JOURS`;$("perfect").textContent=`BONUS PERFECT DAY : ${fmt(s.perfectDayBonus)} XP`;
  const ev=evol.find(x=>s.global.level>=x[0]);$("rank").textContent=ev[1];let v=$("avatarVideo"),src=`ps4_media/${ev[2]}_idle.mp4`;if(v.dataset.src!==src){v.dataset.src=src;v.src=src;v.play().catch(()=>{})}
  renderAnalysis();renderObjectives();renderDifficulty();settings();
 }
 function renderAnalysis(){if(!S)return;let a=S.attrs;$("analysisBody").innerHTML=`<div class="analysis-grid"><div class="metricbox"><small>XP NETS</small><b>${fmt(S.globalXp)}</b></div><div class="metricbox"><small>XP BRUTS</small><b>${fmt(S.grossXp)}</b></div><div class="metricbox"><small>PÉNALITÉS</small><b>-${fmt(S.penaltyTotal)}</b></div><div class="metricbox"><small>COMEBACK</small><b>+${fmt(S.comebackBonus)}</b></div><div class="metricbox"><small>JOURS SAISIS</small><b>${S.activeDays}</b></div><div class="metricbox"><small>PERFECT DAY</small><b>${fmt(S.perfectDayBonus/50)}</b></div><div class="metricbox"><small>STREAK TABAC</small><b>${S.smoking.streak} j</b></div><div class="metricbox"><small>SPORT SEMAINE</small><b>${S.sportWeek.sessions}/${S.goals.sport}</b></div></div><div class="analysis-bars">${Object.entries(a).map(([k,v])=>`<div class="analysis-row"><span>${k.toUpperCase()}</span><div class="bar"><i style="width:${v.progress}%"></i></div><b>NIV. ${v.level}</b></div>`).join("")}</div>`}
 function renderObjectives(){if(!S)return;let x=[["Lecture",S.goals.reading+" pages / jour"],["Apprentissage",S.goals.learning+" min / jour"],["Sport",S.goals.sport+" séances / semaine"],["Nutrition",S.goals.nutrition+" repas conformes / jour"],["Recherche d'emploi",S.goals.work+" action utile / jour"],["Finance",euro(S.finance.monthlyBudget)+" / mois"]];$("objectiveBody").innerHTML=x.map(([a,b])=>`<div class="objective-row"><b>${a}</b><span>${b}</span><small>ACTIF</small></div>`).join("")}
 function renderDifficulty(){if(!S)return;let D=PlayerEngine.DIFFICULTY;$("difficultyGrid").innerHTML=Object.entries(D).map(([n,d])=>`<button class="diff ${+n===S.difficulty.level?"active":""}" data-d="${n}"><b>${["","I","II","III","IV"][n]} — ${d.name}</b><small>Récompenses ×${d.reward.toFixed(2)}<br>Pénalités ×${d.penalty.toFixed(2)}<br>Grâce ${d.grace}<br>Comeback ${d.comeback} XP</small></button>`).join("");document.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{localStorage.setItem("playerDifficulty",b.dataset.d);PlayerDataSync.refresh()})}
 document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-view]").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(b.dataset.view).classList.add("active")});
 $("saveSettings").onclick=()=>{let fd=new FormData($("settingsForm")),o={};for(let[k,v]of fd)o[k]=+v;localStorage.setItem("playerGameSettings",JSON.stringify(o));$("settingsMsg").textContent="Paramètres enregistrés. Recalcul effectué.";PlayerDataSync.refresh()};
 $("saveQuotes").onclick=()=>{let q={top:$("quoteInputTop").value.trim(),player:$("quoteInputPlayer").value.trim()};localStorage.setItem("playerQuotes",JSON.stringify(q));quotes();$("quoteMsg").textContent="Citations enregistrées et affichées sur le dashboard."};
 $("quoteInputTop").oninput=e=>$("quoteTop").textContent="« "+e.target.value+" »";$("quoteInputPlayer").oninput=e=>$("quotePlayer").textContent="« "+e.target.value+" »";
 addEventListener("player-data-update",e=>render(e.detail));
})();